# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.addcommonptC <- function(pt1_x, pt1_y, pt2_x, pt2_y, u1_x, u1_y, u2_x, u2_y, d1, d2, eps = 1.0e-9) {
    .Call('_espadon_addcommonptC', PACKAGE = 'espadon', pt1_x, pt1_y, pt2_x, pt2_y, u1_x, u1_y, u2_x, u2_y, d1, d2, eps)
}

.dicombrowser <- function(dicomrawdata, tagdico, nbTAG = 0L, stop_tag = "", stop_level = 0L, full_info = FALSE, verbose = FALSE) {
    .Call('_espadon_dicombrowser', PACKAGE = 'espadon', dicomrawdata, tagdico, nbTAG, stop_tag, stop_level, full_info, verbose)
}

.fansphereC <- function(angle) {
    .Call('_espadon_fansphereC', PACKAGE = 'espadon', angle)
}

.fantovoxelC <- function(p, n_ijk, k_idx, k_loc, O_ijk, vol_data, att = FALSE, vol_value_flag = FALSE, vol_value = 1.0) {
    .Call('_espadon_fantovoxelC', PACKAGE = 'espadon', p, n_ijk, k_idx, k_loc, O_ijk, vol_data, att, vol_value_flag, vol_value)
}

.gammaindex <- function(vol3D, vol3D_ref, inspect_idx, n_ijk, rel_dxyz, ball_i, ball_j, ball_k, around_idx, distance, D_norm, local, local_th_pc, ref_pc) {
    .Call('_espadon_gammaindex', PACKAGE = 'espadon', vol3D, vol3D_ref, inspect_idx, n_ijk, rel_dxyz, ball_i, ball_j, ball_k, around_idx, distance, D_norm, local, local_th_pc, ref_pc)
}

.getijktfromindexC <- function(index, k_idx, n_ijk) {
    .Call('_espadon_getijktfromindexC', PACKAGE = 'espadon', index, k_idx, n_ijk)
}

.getvaluefromijkC <- function(vol3D, interpolate, i, j, k, k_idx, k_loc, n_ijk) {
    .Call('_espadon_getvaluefromijkC', PACKAGE = 'espadon', vol3D, interpolate, i, j, k, k_idx, k_loc, n_ijk)
}

.isoclineC <- function(it1, it2) {
    .Call('_espadon_isoclineC', PACKAGE = 'espadon', it1, it2)
}

.labelbrowser <- function(vol3D, n_ijk) {
    .Call('_espadon_labelbrowser', PACKAGE = 'espadon', vol3D, n_ijk)
}

.mdcC <- function(vol3Dref, n_ijk, dxyz, Testi, Testj, Testk) {
    .Call('_espadon_mdcC', PACKAGE = 'espadon', vol3Dref, n_ijk, dxyz, Testi, Testj, Testk)
}

.mean_voxC <- function(vol3D, index, index_list, value_list, value_att_list) {
    .Call('_espadon_mean_voxC', PACKAGE = 'espadon', vol3D, index, index_list, value_list, value_att_list)
}

.medianfilterC <- function(vol3D, n_ijk, analyse_idx_vect, ball_i, ball_j, ball_k) {
    .Call('_espadon_medianfilterC', PACKAGE = 'espadon', vol3D, n_ijk, analyse_idx_vect, ball_i, ball_j, ball_k)
}

.meshinfront <- function(pt_x, pt_y, pt_z, p2_x, p2_y, p2_z, u_x, u_y, u_z, n_A, n_B, n_C) {
    .Call('_espadon_meshinfront', PACKAGE = 'espadon', pt_x, pt_y, pt_z, p2_x, p2_y, p2_z, u_x, u_y, u_z, n_A, n_B, n_C)
}

.ptinpolygonC <- function(point_x, point_y, pol_x, pol_y, eps = 1.0e-9) {
    .Call('_espadon_ptinpolygonC', PACKAGE = 'espadon', point_x, point_y, pol_x, pol_y, eps)
}

.ptnearestC <- function(pt1_x, pt1_y, pt1_z, pt2_x, pt2_y, pt2_z, full_info) {
    .Call('_espadon_ptnearestC', PACKAGE = 'espadon', pt1_x, pt1_y, pt1_z, pt2_x, pt2_y, pt2_z, full_info)
}

.roiinterC <- function(pt1_x, pt1_y, u1_x, u1_y, d1, pt2_x, pt2_y, eps = 1e-9) {
    .Call('_espadon_roiinterC', PACKAGE = 'espadon', pt1_x, pt1_y, u1_x, u1_y, d1, pt2_x, pt2_y, eps)
}

