# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dicombrowser <- function(dicomrawdata, tagdico, nbTAG = 0L, stop_tag = "", stop_level = 0L, full_info = FALSE, verbose = FALSE) {
    .Call('_espadon_dicombrowser', PACKAGE = 'espadon', dicomrawdata, tagdico, nbTAG, stop_tag, stop_level, full_info, verbose)
}

.getvaluefromijkC <- function(vol3D, interpolate, i, j, k, k_idx, k_loc, n_ijk) {
    .Call('_espadon_getvaluefromijkC', PACKAGE = 'espadon', vol3D, interpolate, i, j, k, k_idx, k_loc, n_ijk)
}

.labelbrowser <- function(vol3D, n_ijk) {
    .Call('_espadon_labelbrowser', PACKAGE = 'espadon', vol3D, n_ijk)
}

